// ---------------------------------------------------------------------------
// Base de conhecimento do assistente de suporte.
//
// MANUTENCAO: espelha as abas do manual em src/pages/Suporte.tsx (GUIDE_TABS) e
// os guias em src/components/suporte/*Guide.tsx. Alterou um guia? Atualize a
// entrada correspondente aqui no MESMO commit, senao a IA passa a orientar errado.
// ---------------------------------------------------------------------------

/**
 * As rotas abaixo sao escritas relativas (fonte unica com o front), mas TUDO que
 * sai daqui para o prompt/tools ja vai como URL ABSOLUTA — a IA precisa mandar o
 * link completo para o cliente conseguir clicar.
 */
const APP_URL = (Deno.env.get("APP_PUBLIC_URL") ?? "https://app.clinbia.ai").replace(/\/+$/, "");

const abs = (path: string) => (path.startsWith("http") ? path : `${APP_URL}${path}`);

export interface SupportTopic {
    /** = value da aba em GUIDE_TABS */
    id: string;
    label: string;
    /** rota do manual */
    route: string;
    /** tours guiados disponiveis (src/lib/suporteTours.ts) */
    tours?: { label: string; url: string }[];
    /** duvidas que essa aba responde */
    resolves: string[];
    /** passo a passo curto */
    steps: string[];
    /** armadilhas / regras que costumam gerar chamado */
    gotchas?: string[];
}

export const SUPPORT_TOPICS: SupportTopic[] = [
    {
        id: "dashboard",
        label: "Dashboard",
        route: "/suporte?tab=dashboard",
        tours: [
            { label: "Conhecer as abas", url: "/dashboard?tour=dashboard-abas" },
            { label: "Monitoramento", url: "/dashboard?tab=monitoramento&tour=monitoramento-tour" },
        ],
        resolves: [
            "onde vejo os numeros da clinica",
            "quantos atendimentos cada colaborador fez",
            "quanto estou gastando com IA e com mensagens da Meta",
            "quantos agendamentos foram feitos no periodo",
            "nota de satisfacao (NPS) dos pacientes",
            "liberar abas do Dashboard para supervisor ou atendente",
            "o colaborador nao ve a aba Vendas / Monitoramento / Satisfacao do Dashboard",
            "os quadros do Monitoramento aparecem fechados / sumiram os cards",
            "o que significa a cor do contorno do card no Monitoramento",
            "o card do Monitoramento nao mostra a janela de 24h",
            "onde vejo Sem Contato e Sem Interesse na aba CRM",
            "como filtrar a aba CRM por hoje, 7 dias, 30 dias ou periodo personalizado",
            "os numeros da aba CRM estao menores do que o funil do CRM",
            "quero ver QUEM sao os clientes que ficaram em Ganho, Perdido, Sem Contato ou Sem Interesse",
            "como abrir o ticket (conversa) de uma negociacao a partir do Dashboard",
            "quero entender o motivo de uma nota baixa na aba Satisfacao",
            "como ver a conversa do cliente que deu a nota de NPS",
        ],
        steps: [
            "Abra Dashboard no menu lateral.",
            "Escolha a aba: Minha Conta (custos, conexoes, colaboradores), Monitoramento (conversas em andamento por etapa), CRM, Vendas, Agendamentos, Campanhas, Recorrencia e Satisfacao.",
            "Use o filtro de periodo no topo — ele vale para todos os cards da aba.",
            "Para liberar uma aba a um supervisor ou atendente: Equipe > aba Permissoes > abra o bloco do nivel > subcategoria 'Abas do Dashboard' > ligue a chave Acesso da aba > Salvar. A pessoa precisa recarregar a pagina.",
        ],
        gotchas: [
            "Admin sempre ve todas as abas. Para supervisor e atendente cada aba tem uma chave propria em Equipe > Permissoes > Abas do Dashboard.",
            "Padrao: supervisor ve tudo menos Minha Conta; atendente ve apenas o CRM. Isso pode ser mudado nas permissoes.",
            "Se nenhuma aba estiver liberada, a pagina Dashboard some do menu daquela pessoa.",
            "Link direto para uma aba bloqueada nao da erro: o sistema cai na primeira aba liberada.",
            "Minha Conta expoe custos de IA e Meta — so ligue para supervisor/atendente se quiser mostrar os valores da conta.",
            "O custo da Meta e uma ESTIMATIVA por categoria de template, nao a fatura oficial da Meta.",
            "A aba CRM do Dashboard conta MOVIMENTACAO no periodo: quantas negociacoes ENTRARAM em cada etapa dentro do filtro. Nao e o total parado na etapa — para ver a foto atual do funil use a pagina CRM.",
            "Todas as secoes da aba CRM (Resultados, Monitoramento CRM, Filas e Negociacoes) tem o mesmo filtro: Hoje, Ultimos 7 dias, Ultimos 30 dias ou Personalizado (data inicial e final).",
            "Resultados mostra os 5 desfechos: Ganho, Perdido, Sem Contato, Sem Interesse e Finalizado.",
            "Cada card de Resultados e clicavel: abre a lista das negociacoes daquele desfecho no periodo, com nome do cliente, quando entrou na etapa, inicio e fim do ticket, quem atendeu, quantas mensagens foram trocadas e a negociacao vinculada (valor e servicos).",
            "Clicar em uma negociacao dessa lista abre o ticket no Inbox — a conversa que estava em andamento quando o card mudou de etapa. Conversa ja encerrada abre normalmente, com o historico completo.",
            "Selo 'Sem ticket' na lista: nao existe conversa daquele contato naquela conexao (negociacao criada na mao no funil ou importada). Os demais dados valem; so nao ha chat para abrir.",
            "Uma negociacao conta uma vez so, na ULTIMA etapa em que entrou dentro do periodo. Se ela andou Qualificado > Agendado > Ganho no mesmo dia, aparece apenas em Ganho.",
            "Numeros de Hoje sao naturalmente baixos e mudam ao longo do dia; para comparar volume use 7 ou 30 dias.",
            "As tres linhas do card (Aberto, Pendente, Concluido) somam o total e mostram a situacao ATUAL da conversa do contato. Concluido costuma ser alto nos desfechos porque a etapa terminal encerra a conversa.",
            "No Monitoramento todos os quadros de fila (incluindo Finalizados) abrem FECHADOS. Nada sumiu: a contagem entre parenteses no titulo mostra quantas conversas tem em cada fila; clique no titulo para expandir.",
            "Contorno do card no Monitoramento: LARANJA = o cliente falou por ultimo e ninguem respondeu; VERDE = a ultima mensagem saiu da equipe ou da IA. Nos cards do quadro Finalizados o contorno e a cor da etapa de conclusao.",
            "A contagem da janela de 24h so aparece em conversa de numero oficial (WhatsApp da Meta e Instagram). Na API nao oficial (QR Code) esse prazo nao existe, entao o card nao mostra contagem — nao e erro.",
            "Na aba Satisfacao, em 'Ultimas Avaliacoes NPS', o nome do cliente e um link: clicando nele abre a conversa daquele atendimento (com o historico anterior do contato) para entender o contexto da nota.",
            "Avaliacao de contato apagado nao vira link — o nome aparece como texto simples, sem chat para abrir.",
        ],
    },
    {
        id: "inbox",
        label: "Inbox",
        route: "/suporte?tab=inbox",
        tours: [
            { label: "Atender um cliente", url: "/?tour=inbox-atender" },
            { label: "Filtros avancados", url: "/?tour=inbox-filtros" },
            { label: "Transferir atendimento", url: "/?tour=inbox-transferir" },
            { label: "Notas internas", url: "/?tour=inbox-notas" },
        ],
        resolves: [
            "como atender uma conversa",
            "como transferir a conversa para outro colaborador ou fila",
            "como encerrar (resolver) um atendimento",
            "por que nao vejo a conversa de um cliente",
            "como filtrar por fila, tag, etapa do CRM, conexao ou usuario",
            "onde vejo os atendimentos antigos do mesmo cliente",
            "como mandar audio, imagem, responder, reagir ou apagar mensagem",
            "como deixar uma nota interna que o cliente nao ve",
            "onde vejo o resumo da conversa feito pela IA",
            "por que a conversa encerrada nao tem resumo",
        ],
        steps: [
            "Abra Inbox (pagina inicial). A lista da esquerda traz as conversas; o funil abre os Filtros Avancados.",
            "Os Filtros Avancados tem cinco grupos: Filas, Tags, Etapas do CRM, Instancias e Usuarios. Pode marcar varios: dentro do grupo vale OU, entre grupos vale E. 'Limpar Filtros' zera tudo.",
            "Clique na conversa para abrir o chat. 'Atender' assume a conversa (a IA para de responder) e 'Resolver' encerra e arquiva.",
            "Para passar adiante use o botao de transferencia no topo do chat: primeiro a fila, depois o responsavel. A troca de fila deixa no meio da conversa uma pill azul com a hora, a fila de origem, a de destino e o nome de quem transferiu.",
            "O painel da direita (passe o mouse para expandir) traz dados do cliente, etapa do CRM, negociacao rapida e os tickets anteriores.",
            "O botao roxo de nota (icone de bloco) grava uma observacao interna na conversa — o cliente nunca ve.",
            "Assim que a conversa e encerrada, a IA le o historico daquele atendimento e grava um resumo com a nota de sentimento. Ele aparece na secao 'Resumo' do painel da direita e na aba 'Resumos' do perfil do cliente.",
        ],
        gotchas: [
            "Atendente com escopo configurado so enxerga as conexoes, filas e tags liberadas para ele; conversa ja atribuida a outro colega tambem fica invisivel.",
            "Conversa encerrada tem as mensagens arquivadas: o historico aparece dentro da propria conversa do cliente, nao some.",
            "Ao abrir um ticket anterior pelo painel lateral, o recorte e SOMENTE LEITURA e nao existe botao de reabrir: cada cliente tem um ticket unico por conexao e a conversa continua nele. Use 'Retornar para a conversa geral'.",
            "A secao 'Tickets anteriores' tem filtro por data: botao de calendario mais um seletor Fechamento | Abertura (Fechamento e o padrao). No calendario so os dias que tem ticket ficam clicaveis — dia cinza significa que nao houve atendimento naquela data, pelo campo escolhido. O X ao lado limpa o filtro.",
            "Numero oficial da Meta nao permite editar nem apagar mensagem — esses botoes so aparecem na conexao nao oficial.",
            "Na lista de templates (modal Enviar Template e modal de nova mensagem) existem abas por tipo de template e o campo 'Buscar template...' que filtra pelo nome. Se o template nao aparece, confira a aba selecionada e se ele esta APROVADO na Meta — a lista so mostra aprovados.",
            "Download de documento: clique no botao com o nome do arquivo dentro da mensagem ou no icone de download em 'Midias e arquivos'. O arquivo e salvo com o nome e a extensao originais (.xml continua .xml, .pdf continua .pdf). Se alguem reclamar de arquivo baixado com extensao errada (por exemplo .excel), peca para atualizar a pagina: versoes antigas do site deixavam o navegador adivinhar a extensao.",
            "A pill de transferencia so mostra o nome quando a troca de fila foi feita por uma pessoa logada; troca automatica (IA devolvendo o atendimento, encerramento automatico, campanha, API) aparece como 'pelo sistema'. Avisos de transferencia anteriores a setembro/2026 nao tem autor e ainda mostram o codigo da conversa no inicio do texto.",
            "Conversa de grupo nunca fica atribuida a um colaborador e e visivel para todos, salvo se o grupo for restrito.",
            "O filtro 'Etapas do CRM' olha a etapa do card ATIVO do cliente no funil. Cliente sem card ativo e conversa de grupo (que nao tem card) ficam de fora enquanto o filtro estiver marcado — por isso a aba Grupos aparece vazia com ele ligado.",
            "Os filtros avancados ficam salvos no navegador: continuam ligados depois de atualizar a pagina ou sair e voltar. Se 'sumiram conversas', confira o funil antes de suspeitar de escopo ou permissao.",
            "O resumo automatico vale para QUALQUER forma de encerramento: botao Resolver, encerramento automatico por inatividade, etapa final do CRM, campanha ou API. O resumo e por atendimento (cada ticket tem o seu, so com o que foi falado ali) — nao e um resumo geral do cliente.",
            "O resumo nao sai na hora: ele entra numa fila e leva alguns minutos depois do encerramento. Conversa encerrada sem nenhuma mensagem nao gera resumo. Resumos de atendimentos antigos foram gerados em lote e foram aparecendo aos poucos.",
        ],
    },
    {
        id: "crm",
        label: "CRM",
        route: "/suporte?tab=crm",
        tours: [{ label: "Conhecer o quadro", url: "/crm?tour=crm-board" }],
        resolves: [
            "como funciona o funil e as etapas",
            "por que o card voltou sozinho para outra etapa",
            "o que sao etapas terminais",
            "como registrar servicos e valores da negociacao",
            "diferenca entre Contato, Lead e Cliente",
        ],
        steps: [
            "Abra CRM no menu lateral: cada coluna e uma etapa e cada card e um cliente com negociacao ativa.",
            "Arraste o card para mudar de etapa — a fila do atendimento muda junto, automaticamente.",
            "Clique no card para abrir a negociacao e lancar servicos, valores e agendamento.",
        ],
        gotchas: [
            "Etapa e fila andam juntas nos DOIS sentidos: mover o card muda a fila da conversa e mudar a fila move o card.",
            "Etapas terminais (Ganho, Perdido, Sem Contato, Sem Interesse, Finalizado) encerram a conversa do cliente e viram historico.",
            "Se a IA da conta ou da conexao estiver desligada, o card nao entra nas etapas de IA — vai para atendimento humano.",
            "Cada contato tem no maximo UMA negociacao ativa.",
        ],
    },
    {
        id: "servicos",
        label: "Servicos",
        route: "/suporte?tab=servicos",
        tours: [{ label: "Cadastrar servicos", url: "/products-services?tour=servicos-tour" }],
        resolves: [
            "como cadastrar servicos e precos",
            "como usar os templates prontos de catalogo",
            "como vincular profissionais a um servico",
            "onde configuro as mensagens de recorrencia do servico",
            "onde coloco o valor cobrado no convenio",
            "para que serve a aba Convenio da pagina Servicos",
            "como nomear a aplicacao sem repetir o nome do servico",
            "por que o nome aparece como 'Servico - Aplicacao' em vendas, agenda e mensagens",
        ],
        steps: [
            "Abra Servicos no menu lateral.",
            "Use o botao azul 'Utilizar templates' para importar um catalogo pronto (categorias, servicos e aplicacoes) e ajustar antes de salvar.",
            "Ou crie do zero: Adicionar Categoria, depois o servico e as aplicacoes com preco e duracao.",
            "No lapis do servico voce vincula profissionais e configura as mensagens de recorrencia.",
            "Valor de convenio: marque o servico no plano em Equipe > Convenios; depois, em Servicos, clique no lapis da aplicacao e preencha 'Valor de Convenio (R$)'.",
            "Com convenio cadastrado, a pagina ganha duas abas no topo: 'Servicos regulares' e 'Convenio'. A aba Convenio tem a MESMA estrutura (categorias, servicos e tabela de aplicacoes), so que exibindo apenas o que esta marcado em algum plano.",
        ],
        gotchas: [
            "O nome da aplicacao NAO repete o nome do servico: na aplicacao entra so o que varia (area e numero de sessoes, ex.: 'Face - 1 sessao'). O sistema junta os dois na exibicao e mostra 'Servico - Aplicacao' em vendas, orcamentos, agenda, relatorios, link publico de agendamento e nas mensagens automaticas. Repetir o nome produz textos como 'Hifu Ultraformer - Hifu Ultraformer Face 1 sessao'.",
            "O nome composto e montado na HORA DE EXIBIR, a partir do cadastro atual: corrigir o nome no catalogo corrige a apresentacao em toda a plataforma, inclusive em vendas e agendamentos antigos.",
            "Categoria do tipo direto (Consultas/Avaliacao) nao tem o nivel do servico — nesses casos aparece so o nome da aplicacao, sem prefixo.",
            "O preco cadastrado no servico e a fonte unica: valor digitado em planilha de importacao nao altera o cadastro.",
            "As abas 'Servicos regulares' e 'Convenio' so aparecem quando existe pelo menos um convenio cadastrado em Equipe > Convenios; a coluna 'Valor convenio' (ao lado de Valor) so aparece quando existe pelo menos um servico marcado em algum plano (Equipe > Convenios > Configurar).",
            "Todo convenio cadastrado cobre AUTOMATICAMENTE os servicos da categoria 'Avaliacao' — por isso a Avaliacao aparece na aba Convenio mesmo sem ninguem ter marcado nada, e a coluna 'Valor convenio' ja fica visivel.",
            "O valor de convenio e UM SO por aplicacao, mesmo com varios planos cadastrados — nao existe preco por convenio.",
            "Valor de convenio em cinza = campo em branco: a aplicacao esta cobrando o proprio valor de venda e acompanha os reajustes dele. Digite um valor para congelar um preco so do convenio.",
            "Na aba Convenio nao da para criar nem excluir (so editar e ligar/desligar) e os botoes de adicionar do topo somem: a aplicacao mora na aba Servicos regulares, que e onde ela e criada e apagada.",
            "A categoria 'Avaliacao' e protegida — nao pode ser renomeada nem excluida (o link publico de agendamento e a regra de orcamento dependem dela). Avaliacao nao e vendida por orcamento, so agendada.",
            "Servico sem sala vinculada bloqueia o lancamento da venda do orcamento: vincule as salas no lapis do servico.",
            "A pagina so lista categorias que ja tenham pelo menos um servico cadastrado.",
        ],
    },
    {
        id: "orcamentos",
        label: "Orcamentos",
        route: "/suporte?tab=orcamentos",
        tours: [
            { label: "Criar um orcamento", url: "/?tour=orcamento-criar" },
            { label: "Ver os numeros dos orcamentos", url: "/financial?tour=financeiro-visao-geral" },
        ],
        resolves: [
            "como fazer um orcamento para o cliente",
            "como lancar a venda de um orcamento",
            "o que significam os icones de status do orcamento (relogio, check, x)",
            "por que o orcamento sumiu da lateral do inbox",
            "por que nao consigo excluir ou editar um orcamento",
            "por que o servico de avaliacao nao aparece no orcamento",
            "onde vejo tudo o que o cliente ja comprou e o valor movimentado",
            "como exportar o orcamento em pdf para enviar ao paciente",
            "como personalizar o cabecalho e o rodape do orcamento em pdf",
            "qual o tamanho certo da imagem do cabecalho do orcamento",
        ],
        steps: [
            "O orcamento nasce na conversa: abra o Inbox, entre na conversa do cliente e clique no menu Orcamento na barra lateral direita.",
            "Clique em 'Realizar orcamento', escolha os servicos (categoria > servico > aplicacao) com a quantidade, selecione o Profissional (obrigatorio), preencha a Indicacao (de onde veio o cliente, opcional) e a Validade (opcional).",
            "Quando o cliente aceitar, clique em 'Lancar venda' no card: passo 1 marque Vender ou Remover em cada item (o valor e editavel); passo 2 defina Sala, Forma de pagamento, Data do pagamento e se vai agendar agora; passo 3 preencha os agendamentos; passo 4 revise e confirme.",
            "Se responder 'nao' para agendar, ligue o switch 'Agendamento pela IA' e informe em quantos dias a IA deve procurar o cliente.",
            "Todos os orcamentos do cliente (abertos e resolvidos) ficam no perfil dele: Clientes > clique no nome > aba Orcamentos. As vendas ficam na aba Vendas e a soma de tudo aparece como 'Valor movimentado' na lateral do perfil.",
            "Para ver os numeros de TODOS os orcamentos (valores totais, aprovados, rejeitados e pendentes, ranking por profissional e por servico), abra a pagina Financeiro > aba Orcamentos. Da para criar orcamento por la tambem, escolhendo o cliente na busca.",
            "Para exportar em PDF: no perfil do cliente (Clientes > nome > aba Orcamentos) cada card tem o botao 'Exportar PDF'; no Financeiro > aba Orcamentos o icone de download fica na ultima coluna da tabela. O arquivo baixa como Orcamento_Nome_Do_Cliente_dd-mm-aaaa.pdf.",
            "Para personalizar o PDF: Configuracoes > aba Empresa > bloco 'Orcamento em PDF'. Ali voce envia o cabecalho em PNG (botao 'Enviar imagem'), baixa um modelo pronto no tamanho certo (botao 'Baixar modelo') e escreve o rodape (texto livre com condicoes de pagamento, CNPJ, endereco, politica de validade).",
        ],
        gotchas: [
            "Toda venda passa por orcamento. A unica excecao e a categoria Avaliacao, que nao e vendida — so agendada (ela nem aparece no seletor do orcamento).",
            "A lateral do Inbox mostra apenas orcamentos com item pendente e dentro da validade; os resolvidos ou expirados vivem no perfil do cliente.",
            "Os icones falam de VENDA, nunca de agendamento: relogio = o cliente ainda nao comprou, check verde = vendido, x vermelho = recusado, x cinza = expirado.",
            "Exclusao so e permitida enquanto TODOS os itens estao pendentes; depois que um item vira vendido ou recusado, da para editar apenas os pendentes e a exclusao fica bloqueada.",
            "No passo 2 so aparecem as salas atreladas aquele procedimento. Sem sala vinculada o assistente bloqueia — vincule em Servicos (lapis do servico) e volte.",
            "Atendente e Profissional nao sao editaveis no assistente: o atendente e quem esta logado e o profissional vem do orcamento.",
            "Cada unidade da quantidade e uma linha independente, com valor e status proprios (da para vender uma e o cliente recusar a outra).",
            "Orcamento nao movimenta o CRM e nao existe em conversa de grupo.",
            "Por padrao o atendente pode criar e editar orcamento mas nao pode excluir nem lancar venda — o gestor libera em Equipe > Permissoes (modulos Orcamentos e Vendas).",
            "Orcamento vencido vira somente leitura automaticamente (rotina diaria de madrugada): nao da para editar, excluir nem lancar venda.",
            "O PDF exportado lista SOMENTE os itens pendentes — e o documento que vai para a mao do paciente, entao o que ja foi vendido ou recusado nao aparece. Orcamento com tudo decidido nao tem botao de exportar.",
            "Exportar PDF nao depende de permissao de venda nem da validade: mesmo orcamento expirado ou so-leitura pode ser exportado, desde que tenha item pendente.",
            "Cabecalho do PDF: arquivo PNG de ate 2 MB, tamanho ideal 2400x400 pixels (proporcao 6:1, equivale a faixa de 210x35 mm no topo da folha A4). Deixe ~40 pixels de margem nas bordas e evite texto branco (o PDF e impresso em branco). Fundo transparente e aceito.",
            "Enquanto a conta nao envia nenhum cabecalho, o PDF sai com uma faixa azul contendo o nome e o telefone da empresa (cadastrados em Configuracoes) — o botao Exportar funciona desde o primeiro dia.",
            "O cabecalho e o rodape valem para a CONTA inteira, nao por colaborador. So quem tem permissao em 'Dados da empresa' consegue alterar.",
        ],
    },
    {
        id: "clientes",
        label: "Clientes",
        route: "/suporte?tab=clientes",
        tours: [{ label: "Conhecer a pagina", url: "/contacts?tour=clientes-tour" }],
        resolves: [
            "como cadastrar, importar ou exportar clientes",
            "o que significa Contato, Lead e Cliente",
            "como ver o perfil completo, historico e documentos",
            "como desligar a IA para um cliente especifico",
            "como usar tags (etiquetas)",
            "onde ficam os resumos das conversas do cliente",
        ],
        steps: [
            "Abra Clientes no menu lateral.",
            "Clique no nome do cliente para abrir o perfil completo (cadastro, orcamentos, vendas, agendamentos, atendimentos, historico, avaliacao, resumos e negociacoes).",
            "O switch de IA na linha do cliente e o UNICO lugar que desliga a IA para aquele contato.",
            "A aba 'Resumos' do perfil lista um resumo por atendimento encerrado, do mais recente para o mais antigo, com a data e a nota de sentimento (0 a 10).",
        ],
        gotchas: [
            "A categoria (Contato/Lead/Cliente) e automatica pelas vendas: so avaliacao = Lead, qualquer outro servico = Cliente.",
            "Os resumos da aba 'Resumos' sao gerados sozinhos quando a conversa e encerrada — um por atendimento, so com o que foi falado naquele ticket. Se o cliente teve 5 atendimentos, aparecem 5 resumos. Nao existe resumo unico juntando tudo.",
            "Nada no sistema desliga a IA de um contato sozinho — se a IA parou, verifique a fila da conversa, a IA da conexao e o switch geral.",
            "Etiqueta de campanha e removida quando a campanha e encerrada ou quando o cliente nao recebeu a mensagem.",
        ],
    },
    {
        id: "equipe",
        label: "Equipe",
        route: "/suporte?tab=equipe",
        tours: [
            { label: "Conhecer a pagina", url: "/equipe?tour=equipe-tour" },
            { label: "Cadastrar um convenio", url: "/equipe?tab=convenios&tour=convenio-cadastrar" },
        ],
        resolves: [
            "como convidar um colaborador",
            "diferenca entre Administrador, Supervisor e Atendente",
            "como limitar o que o atendente enxerga",
            "como liberar ou bloquear paginas para um cargo",
            "como liberar abas do Dashboard para supervisor ou atendente",
            "quem esta online agora",
            "diferenca entre profissional e sala",
            "como cadastrar um profissional ou uma sala",
            "como inativar ou excluir um profissional ou uma sala",
            "como cadastrar um convenio",
            "como dizer que a clinica atende todos os convenios",
            "como definir quais servicos sao atendidos por convenio",
            "por que nao consigo desmarcar a avaliacao do convenio",
            "como reservar dias e horarios so para convenio",
            "por que a IA nao oferece horario de convenio",
            "por que a sala nao aparece na lista de salas do convenio",
        ],
        steps: [
            "Abra Equipe no menu lateral. Sao cinco abas: Equipe Comercial, Profissionais, Salas, Convenios e Permissoes.",
            "Equipe Comercial: clique em adicionar membro, informe nome, e-mail, senha e cargo. No mesmo modal defina o escopo do Atendente: conexoes, filas e tags visiveis.",
            "Profissionais: quem atende na clinica (nome, cargo, foto e horarios). Ao salvar, a sala dele e criada automaticamente com o mesmo nome.",
            "Salas: as agendas — as de profissional e as avulsas (botao Adicionar Sala), para consultorio, equipamento ou espaco compartilhado.",
            "Convenios: cadastre o plano (nome e descricao opcional), marque os servicos atendidos por categoria e marque as salas que recebem esse plano. Os servicos da categoria 'Avaliacao' ja vem marcados e travados — todo convenio atende avaliacao. Se a clinica aceita qualquer plano, ligue a chave 'Habilitar todos os convenios' no topo da aba.",
            "Os dias e o horario reservados ao convenio ficam no cadastro da SALA (abas Salas ou Profissionais), logo abaixo dos Dias de Atendimento: ligue 'Atendimento de Convenio', escolha os dias e a faixa de inicio e fim (da para configurar dia a dia).",
            "A aba Permissoes (somente Administrador) libera modulo a modulo: Criar, Editar e Apagar por modulo.",
            "No fim da lista de modulos existe a subcategoria 'Abas do Dashboard', com uma chave de Acesso por aba do Dashboard (Minha Conta, Monitoramento, CRM, Vendas, Agendamentos, Campanhas, Recorrencia e Satisfacao). E por ela que se libera aba do Dashboard para Atendente.",
        ],
        gotchas: [
            "Escopo vazio = ve tudo. Escopo preenchido combina os tres criterios ao mesmo tempo.",
            "Abas do Dashboard: padrao supervisor ve tudo menos Minha Conta e atendente ve apenas o CRM. Sem nenhuma aba ligada, a pagina Dashboard some do menu da pessoa.",
            "Depois de salvar permissoes, a pessoa precisa recarregar a pagina para ver a mudanca.",
            "Atendente com escopo de tags nao ve conversa de cliente sem etiqueta.",
            "A aba Permissoes e sempre exclusiva do Administrador, mesmo para supervisor liberado.",
            "Cada coluna da agenda e uma SALA. Profissional e sala andam juntos: renomear um renomeia o outro e inativar o profissional inativa a sala dele.",
            "Inativar CANCELA todos os agendamentos futuros daquela agenda — o sistema avisa antes de confirmar.",
            "Nao e possivel EXCLUIR profissional ou sala com agendamento futuro: remarque ou cancele antes, ou apenas inative para preservar o historico.",
            "A sala de um profissional nao pode ser inativada sozinha; inative o profissional. Sala avulsa pode.",
            "Convenio depende de QUATRO elos: o convenio cadastrado, o servico marcado nele, a sala marcada nele e o horario de convenio configurado nessa sala. Faltando qualquer um, a busca de horario de convenio volta vazia.",
            "Nao da para DESMARCAR a avaliacao de um convenio, e isso e proposital: os servicos da categoria 'Avaliacao' entram automaticamente em todo convenio cadastrado (aparecem marcados e travados no seletor). Vale nos dois sentidos — avaliacao criada depois entra sozinha nos convenios ja existentes.",
            "So aparece na lista de salas do convenio a sala que esta com 'Atendimento de Convenio' ligado no proprio cadastro.",
            "A faixa reservada ao convenio SAI das buscas de horario particular da IA, do link publico e das integracoes; nas buscas de convenio so aparecem essas faixas, e so nas salas marcadas para aquele plano.",
            "Marcar a agenda manualmente pelo painel continua LIVRE dentro da faixa de convenio — na grade ela e apenas pintada de amarelo, como aviso visual.",
            "A faixa de convenio precisa caber dentro do expediente da sala: o que ficar fora do horario de atendimento (ou dentro do intervalo) e ignorado.",
            "Com 'Habilitar todos os convenios' ligado, a IA responde 'Habilitado para todos os convenios' em vez de listar nomes e a lista cadastrada fica guardada sem uso. Os servicos e salas desse modo geral sao configurados no botao Configurar.",
            "Marcar o servico no convenio libera, na pagina Servicos, a coluna 'Valor convenio' e a aba 'Convenio' (mesma estrutura de categorias/servicos/aplicacoes, so com o que o plano cobre). O valor cobrado no plano e definido no lapis da aplicacao (campo 'Valor de Convenio (R$)'), e um so para todos os planos, e em branco acompanha o valor de venda.",
        ],
    },
    {
        id: "agenda",
        label: "Agenda",
        route: "/suporte?tab=agenda",
        tours: [{ label: "Conhecer a agenda", url: "/scheduling?tour=agenda-tour" }],
        resolves: [
            "como criar, remarcar ou cancelar um agendamento",
            "como configurar o horario de trabalho da sala / do profissional",
            "como fechar a agenda em um dia",
            "por que todo agendamento gerou uma venda",
            "as mensagens automaticas de confirmacao e lembrete",
            "por que a IA nao responde durante a confirmacao automatica",
            "por que a conversa foi encerrada por falta de interacao",
            "como importar agendamentos por planilha",
            "quem marcou um agendamento e em que dia ele foi marcado",
            "por que um profissional nao aparece na grade",
            "como ver so as salas (laser, consultorio, equipamento) na agenda",
            "alternar a agenda entre profissionais e salas",
            "o que e a faixa amarela na agenda",
            "o card que aparece ao passar o mouse fica cortado ou atras do agendamento",
            "agendamento curto (5 ou 10 minutos) aparecendo espremido na grade",
            "dois agendamentos no mesmo horario ficando sobrepostos",
            "como ver a agenda de um profissional so (visao solo)",
            "por que o cliente nao escolhe a sala no link de agendamento",
            "quais salas aparecem para o cliente escolher no link de agendamento",
        ],
        steps: [
            "Abra Agenda no menu lateral. O botao no cabecalho alterna entre grade (dia) e calendario (mes).",
            "Ao lado do botao Hoje ha o alternador Profissionais | Salas: em Profissionais a grade traz so as agendas dos profissionais cadastrados; em Salas, so as salas avulsas (sem profissional vinculado). A lista de botoes da barra lateral acompanha o modo.",
            "Cada coluna da grade e uma SALA (a agenda). Clique num horario livre para abrir o agendamento: cliente, servico, sala e forma de pagamento.",
            "A lista de botoes abaixo do calendario (barra lateral) segue ordem alfabetica, a mesma das colunas da grade. Clicar num botao mostra so aquela agenda; 'Todos' volta a visao geral.",
            "O horario de trabalho fica no cadastro da sala (Equipe > Salas, ou Adicionar Sala na barra lateral da agenda), com opcao de horario diferente por dia da semana.",
            "No mesmo cadastro, abaixo dos dias de atendimento, a chave 'Atendimento de Convenio' reserva dias e uma faixa de horario para pacientes de convenio — ela aparece pintada de amarelo na grade, com a etiqueta Convenio.",
            "Clique num agendamento ja marcado para abrir os Detalhes do Agendamento. No fim do modal, o bloco 'Agendado por' mostra QUEM criou o agendamento, por onde ele entrou e a data e hora em que foi marcado.",
            "Passe o mouse sobre um agendamento para abrir o card flutuante com cliente, telefone, servico, sala, horario, status e quem agendou, alem dos botoes de status (confirmar, concluir, cancelar, falta).",
            "Clique no nome do profissional no cabecalho da coluna para entrar na visao solo (so aquela agenda). A seta ao lado do nome volta para a visao geral.",
        ],
        gotchas: [
            "Primeira coisa a conferir quando 'sumiu uma agenda': o alternador Profissionais | Salas mostra um grupo por vez. Sala avulsa so aparece no modo Salas; profissional so no modo Profissionais.",
            "Profissional ou sala inativa some da grade, do modal de agendamento e do link publico.",
            "No link publico de agendamento so a AVALIACAO deixa o cliente escolher o profissional, e a tela lista apenas as salas que tem um profissional vinculado, mostrando nome e cargo dele. Sala sem profissional vinculado (Equipe > Salas) nao aparece nessa escolha.",
            "Nos servicos ja comprados o link publico NAO mostra a escolha de sala: o cliente vai direto para o calendario, que junta os horarios livres de todas as salas aptas ao servico, e o sistema encaixa sozinho na sala que estiver livre. A sala nao e escolha do paciente. Reagendar pelo link mantem a sala do agendamento original.",
            "O card flutuante do mouse aparece sempre por cima de tudo, mesmo com o agendamento no pe da tela ou colado na borda: ele abre para baixo quando o evento esta no topo e para cima quando esta embaixo. Se ele nao aparecer, verifique se a pagina esta atualizada (Ctrl+F5) — a versao antiga cortava o card dentro da rolagem da grade.",
            "Dois agendamentos que ocupam o mesmo horario ficam LADO A LADO na coluna, com metade da largura cada um. E o caso classico do cancelado com um novo agendamento remarcado para a mesma hora: os dois continuam visiveis, nenhum fica escondido atras do outro. Cancelado e falta aparecem como uma tira fina e apagada.",
            "As linhas da grade seguem o Tamanho do slot de IA > Configuracoes e a coluna da esquerda marca as horas cheias (8:00, 9:00...).",
            "A altura de cada HORA se ajusta sozinha a duracao dos atendimentos daquela faixa: quando ha procedimento curto (menos de 15 minutos, tipo aplicacao de 5 min) a hora dilata — ate 4x — para que o card nao fique uma tirinha ilegivel. So a hora que tem atendimento curto cresce; o resto do dia fica no tamanho de sempre. Quem define isso e a duracao do servico/aplicacao agendado, nao o Tamanho do slot.",
            "Na visao solo (clicando no nome do profissional) a grade fica com o dobro da altura, a coluna de horarios da esquerda passa a marcar de slot em slot (8:00, 8:10, 8:20... conforme o Tamanho do slot de IA > Configuracoes) e cada card mostra o nome do cliente em negrito com horario, servico, data em que o agendamento foi marcado e quem agendou logo abaixo.",
            "Mudar o Tamanho do slot em IA > Configuracoes muda o desenho da grade (e as marcacoes da coluna de horario na visao solo), mas NAO limita o encaixe manual: continua dando para agendar em qualquer minuto pela agenda.",
            "Os horarios oferecidos pela IA e pelo link publico seguem o Tamanho do slot e o Intervalo entre atendimentos configurados em IA > Configuracoes. Quem agenda pela agenda do painel nao sofre essas restricoes.",
            "A faixa amarela 'Convenio' na grade e apenas informativa: o encaixe manual pelo painel continua livre ali dentro. Quem respeita a reserva sao a IA, o link publico e as integracoes — nas buscas de horario particular esses intervalos nao sao oferecidos. Os planos e servicos aceitos ficam em Equipe > Convenios.",
            "No bloco 'Agendado por' dos Detalhes do Agendamento, tudo que foi marcado pela IA ou pelo link publico de agendamento aparece como IA — a linha de baixo diz se veio 'Via API' ou 'Via link de agendamento'. Agendamento feito na propria agenda mostra o nome do colaborador ('Pela agenda') e, quando veio de planilha, o nome de quem subiu a planilha ('Por planilha importada').",
            "Agendamentos antigos aparecem como 'Nao informado' no bloco 'Agendado por': eles foram criados antes de o sistema passar a registrar a autoria. A data e hora em que foram marcados continua aparecendo. Isso nao se corrige — vale para os agendamentos dali em diante.",
            "Remarcar, confirmar ou concluir NAO muda o 'Agendado por': ele guarda quem CRIOU o agendamento, nao quem mexeu nele depois.",
            "Todo agendamento precisa de um cliente vinculado e cria/liga uma venda com pagamento pendente.",
            "Concluir o agendamento NAO cria venda nova — ela ja existe desde a criacao.",
            "As mensagens automaticas (confirmacao 24h, lembrete 2h e pesquisa 24h depois) funcionam independentemente da IA estar ligada.",
            "Na confirmacao e na pesquisa, so o TOQUE NO BOTAO (ou o texto exato do botao) segue o fluxo automatico. Qualquer outra mensagem encerra a mensagem automatica na hora e entrega a conversa para a IA — ou para a fila humana, se a IA estiver desligada. A IA consegue confirmar o agendamento sozinha quando o cliente confirma escrevendo.",
            "Cliente que nao responde nada a mensagem automatica recebe em 24h um aviso de encerramento por falta de interacao e a conversa e resolvida. O agendamento NAO e cancelado, so o atendimento fecha. No numero oficial (Meta) o aviso nao e enviado quando o cliente nunca respondeu, porque a janela de 24h da Meta esta fechada; a conversa fecha em silencio.",
            "Confirmacao e lembrete NAO mudam a etapa do card no CRM nem a fila da conversa. Unica excecao: card parado em 'Pesquisa de Satisfacao' de um atendimento anterior volta para 'Agendado' quando o cliente tem agendamento novo chegando. Se a pesquisa ainda espera resposta, ou se um atendente ja esta conduzindo a conversa, nada e movido.",
            "O follow-up da IA fica desligado para quem tem agendamento nas proximas 24h, ou card ativo nas etapas 'Agendado' e 'Pesquisa de Satisfacao'. E de proposito: nessa janela quem fala com o cliente sao a confirmacao e o lembrete, e o follow-up chegaria por cima delas.",
            "Quem esta no ciclo de confirmacao fica IMUNE ao encerramento automatico de conversas: da mensagem de confirmacao (vespera) ate a pesquisa de satisfacao (um dia depois do atendimento) o ticket nao recebe aviso nem e fechado pela automacao de Configuracoes > Automacoes.",
            "Responder a pesquisa de satisfacao encerra o ticket na hora e finaliza o card do CRM em 'Finalizado'. Quem nao responde a pesquisa tem o ticket encerrado 24h depois do envio.",
        ],
    },
    {
        id: "recorrencia",
        label: "Recorrencia",
        route: "/suporte?tab=recorrencia",
        tours: [{ label: "Configurar recorrencia", url: "/recurrence?tour=recorrencia-config" }],
        resolves: [
            "como fazer o paciente voltar depois de X meses",
            "as 3 abordagens e os prazos de cada uma",
            "como editar as mensagens e usar variaveis",
            "por que a mensagem depende de template aprovado pela Meta",
        ],
        steps: [
            "Configure o intervalo de retorno no proprio servico (lapis do servico em Servicos).",
            "Ajuste as 3 mensagens de abordagem: no padrao da conta (Conexoes > Templates > Recorrencia) ou so para aquele servico.",
            "Acompanhe em Dashboard > aba Recorrencia; as campanhas sao geradas automaticamente todo dia.",
        ],
        gotchas: [
            "Campanhas de recorrencia nao aparecem na pagina Campanhas — elas vivem na aba Recorrencia do Dashboard.",
            "No numero oficial a mensagem precisa de template aprovado pela Meta; alterar o texto gera uma nova versao para aprovar.",
            "Os tempos das 3 abordagens sao sempre manuais, definidos por voce.",
        ],
    },
    {
        id: "campanhas",
        label: "Campanhas",
        route: "/suporte?tab=campanhas",
        tours: [{ label: "Criar campanha", url: "/campanhas?tour=nova-campanha" }],
        resolves: [
            "como criar e disparar uma campanha",
            "como montar o publico e usar variaveis",
            "como colocar um valor fixo numa variavel do template",
            "por que um contato nao recebeu",
            "o que significa cada card do quadro de resultados",
            "como reenviar uma campanha",
            "como ativar a IA na campanha",
            "quando os contatos da planilha entram no cadastro",
            "por que a planilha nao trocou o nome dos contatos",
            "planilha de campanha renomeou meus clientes",
        ],
        steps: [
            "Abra Campanhas no menu lateral e clique em Nova campanha.",
            "O assistente tem 6 etapas: Dados, Audiencia, Tipo, Mensagem, Objetivo e Revisao.",
            "Na etapa Tipo > Promocao os servicos aparecem agrupados por categoria (igual a pagina de Servicos): clique na categoria para abrir a lista e marque os servicos da campanha.",
            "No numero oficial da Meta a mensagem tem que ser um template ja APROVADO; na conexao nao oficial o texto e livre.",
            "Na etapa Mensagem, cada variavel do template ({{1}}, {{2}}...) e ligada a um dado da fonte (nome, telefone, coluna da planilha...) ou a opcao 'Personalizado (valor fixo)', que abre um campo de texto e envia o mesmo valor para todos os contatos.",
            "Depois do disparo, expanda o card da campanha para ver os resultados e a tabela contato a contato.",
        ],
        gotchas: [
            "Cliente com conversa ja aberta nao recebe a campanha (o atendimento em andamento tem prioridade).",
            "Cada contato entra em uma unica campanha ativa por conexao — a campanha nova derruba a anterior uma hora antes do disparo.",
            "Quem nao recebeu a mensagem perde a etiqueta da campanha.",
            "O quadro conta quem RESPONDEU a mensagem da campanha; o inbox filtrado por etiqueta mostra tambem quem so recebeu.",
            "Mensagens automaticas de agendamento tem prioridade sobre campanha no mesmo numero.",
            "O campo opcional da etapa Tipo se chama 'Salas habilitadas' (nao 'profissionais'): marcando alguma, a IA so oferece horarios dessas salas enquanto a campanha estiver ativa; sem nenhuma marcada valem todas. A equipe continua agendando manualmente em qualquer sala.",
            "Variavel 'Personalizado' escolhida mas com o campo em branco impede avancar a etapa Mensagem — digite o texto ou volte para um dado da fonte.",
            "Subir a planilha na etapa Audiencia NAO cadastra contato nenhum: o sistema so procura os numeros (pelos ultimos 8 digitos) para mostrar quantos ja existem. Os que faltam sao criados no instante em que voce cria a campanha. Se desistir no meio do assistente, nada e gravado nos Contatos.",
            "A coluna de nome da planilha nunca sobrescreve o nome de um contato que ja tem nome definido no cadastro — quem manda no nome do cliente e a clinica. A planilha so preenche o nome de contato novo ou de quem ainda estava sem nome. Se uma planilha antiga renomeou seus contatos, os nomes anteriores nao podem ser recuperados: corrija na ficha do cliente.",
        ],
    },
    {
        id: "ia",
        label: "IA",
        route: "/suporte?tab=ia",
        tours: [
            { label: "Configurar a IA", url: "/ia-config?tab=settings&tour=ia-config" },
            { label: "Horarios de agendamento da IA", url: "/ia-config?tab=settings&tour=ia-horarios" },
            { label: "Tom de voz da IA", url: "/ia-config?tab=tone&tour=ia-tom-de-voz" },
            { label: "Ambiente de teste da IA", url: "/ia-sandbox?tour=ia-sandbox" },
        ],
        resolves: [
            "por que a IA nao esta respondendo",
            "como ligar ou desligar a IA (geral, por conexao ou por cliente)",
            "como alimentar a IA com dados da empresa e F.A.Q",
            "como ajustar o tempo de resposta e a voz",
            "quando a IA para de responder sozinha",
            "como mudar o tamanho do slot dos horarios que a IA oferece",
            "como deixar um intervalo entre um atendimento e o proximo",
            "por que a IA oferece horarios de 10 em 10 minutos",
            "a partir de quando conta o tempo do follow-up da IA",
            "por que o cliente nao recebeu o follow-up",
            "como mudar o jeito de a IA falar (tom de voz)",
            "como deixar a IA mais formal, mais proxima ou mais direta",
            "como tratar o cliente por senhor ou por voce",
            "como controlar o uso de emoji pela IA",
            "como fazer a IA insistir mais (ou menos) quando o cliente recua",
            "como testar a IA sem mandar mensagem para cliente nenhum",
            "onde fica o ambiente de teste (sandbox) da IA",
            "como simular campanha, recorrencia, confirmacao de agendamento, venda ou convenio para a IA",
            "quanto custa testar a IA e se esse custo entra na fatura",
            "como limpar a memoria da IA no ambiente de teste",
            "como resetar o ambiente de teste da IA",
        ],
        steps: [
            "Abra IA no menu lateral: aba Empresa (dados e horarios), F.A.Q (perguntas frequentes) e Configuracoes (switch geral, delay, voz, follow-up).",
            "O switch por conexao fica em Conexoes, no card da instancia.",
            "O switch por cliente fica na pagina Clientes.",
            "Em IA > Tom de voz voce ajusta como a IA escreve: seis controles de estilo (proximidade, formalidade, elaboracao, expressividade, assertividade, tecnicidade), o tratamento (voce ou senhor/senhora), a frequencia de emoji (nunca, raro, natural), a Abordagem comercial e um campo opcional 'Sobre a clinica'. A conversa de exemplo ao lado muda na hora. Essa aba tem o Salvar dela.",
            "Em IA > Configuracoes, no bloco 'Horarios de agendamento', escolha o Tamanho do slot (de quantos em quantos minutos os horarios sao oferecidos, padrao 10 min) e o Intervalo entre atendimentos (folga exigida antes e depois de cada agendamento ja marcado, padrao sem intervalo). Clique em Salvar.",
            "Ambiente de teste: em IA > Configuracoes clique em 'Testar IA no ambiente Sandbox'. No topo fica o custo do teste; abaixo o Tom de voz em rascunho; no meio o chat (escreva como o paciente falaria) com o seletor 'Agenda Real' ou 'Agenda Liberada' e o botao 'Limpar memoria'; ao lado o paciente ficticio editavel, 'O que a IA fez', o CRM e os agendamentos/vendas; embaixo os simuladores de campanha, recorrencia, confirmacao de agendamento, venda e convenio. Terminou, clique em 'Resetar ambiente'.",
        ],
        gotchas: [
            "A aba F.A.Q tem um unico campo, geral da clinica. Nao existe mais F.A.Q por produto ou servico: o que e especifico de um procedimento (preco, duracao, descricao) a IA le do cadastro em Servicos.",
            "Para a IA responder e preciso: switch geral ligado, IA ligada NAQUELA conexao, IA ligada no contato, conversa em status pendente e na fila 'Atendimento IA'.",
            "Assim que alguem clica em Atender, a conversa sai da fila da IA e ela para de responder.",
            "Desligar a IA de uma conexao devolve as conversas abertas dela para o atendimento humano.",
            "O tamanho do slot e o intervalo valem para a IA, para o link publico de agendamento e para as automacoes que oferecem horarios. O encaixe MANUAL feito pelo atendente na agenda continua livre.",
            "O tamanho do slot nao muda a duracao do procedimento: a duracao continua vindo do cadastro da aplicacao em Servicos. O slot so define de quanto em quanto tempo os horarios sao oferecidos.",
            "Intervalo alto derruba muito a oferta de horarios: com 30 min de folga, um atendimento das 10h as 11h bloqueia das 9h30 as 11h30.",
            "O tempo do follow-up e contado SEMPRE a partir da ultima mensagem enviada pelo CLIENTE, e de mais nada. Pilula de sistema no chat (transferencia de fila, 'fulano visualizou essa conversa', entrou/saiu do grupo, reacao) e resposta da propria IA nao reiniciam a contagem. Abrir a conversa para dar uma olhada nao atrasa o follow-up.",
            "Conversa em que o cliente nunca escreveu (disparo de campanha sem resposta) nao entra no follow-up: sem mensagem do cliente nao ha relogio para contar.",
            "Follow-up so sai se a ULTIMA fala tiver sido nossa. Se quem falou por ultimo foi o cliente, quem deve resposta somos nos e nenhum follow-up e disparado.",
            "O tom de voz e UNICO por conta: vale para todas as conexoes, WhatsApp e Instagram. Nao existe tom diferente por numero.",
            "O tom muda so o jeito de escrever. O formato das mensagens, as travas de compliance, o fluxo do atendimento e o que esta escrito em Restricoes continuam iguais em qualquer tom. Recusa direta e pedido de descadastro encerram na hora, inclusive na abordagem mais comercial.",
            "A unica excecao e a Abordagem comercial: ela muda comportamento, definindo quantas vezes a IA tenta depois de um recuo do cliente (do aceitar na hora ate sondar o motivo real e tentar tres vezes).",
            "Algumas combinacoes se ajustam sozinhas na tela: formalidade alta com emoji 'natural' volta para 'raro', e abordagem consultiva com assertividade no maximo desce um ponto. O controle se move sozinho e aparece um aviso amarelo embaixo dele. Nao e erro.",
            "O campo 'Sobre a clinica' e descricao, nao ordem: a IA nao promete nem oferece nada com base nele. Texto que tenta instruir a IA ('sempre diga que...', 'insista') e bloqueado no salvar.",
            "Mudanca de tom vale para as PROXIMAS mensagens; o que ja foi respondido nao muda. Se a conversa de exemplo da tela mudou, o tom mudou.",
            "Outros motivos de o follow-up nao sair: conversa nao esta pendente na fila 'Atendimento IA', IA desligada no contato ou naquela conexao, card ativo em Agendado / Sem Interesse / Sem Contato / Pesquisa de Satisfacao, ou agendamento do cliente nas proximas 24h.",
            "O ambiente de teste (sandbox) IGNORA os cinco portoes: nao precisa ligar a IA geral, nem na conexao, nem no contato, e nao importa a fila. Basta ter servicos e salas cadastrados. E o lugar de ajustar a IA antes de soltar para os clientes.",
            "Nada do ambiente de teste toca a conta de verdade: mensagem, agendamento, venda, card de CRM e anotacao ficam em tabelas separadas. Nenhuma mensagem sai por WhatsApp e a agenda, o financeiro e o funil reais nao mudam.",
            "O catalogo usado no teste e o REAL: servicos, salas e convenios sao os cadastrados na conta. So os dados gerados pelo teste sao ficticios.",
            "O consumo do teste e contado a parte e mostrado no topo da propria pagina: nao entra no Relatorio do Consumo nem na fatura. Mesmo assim o teste consome enquanto a conversa continua, por isso resetar ao terminar.",
            "No teste existem DOIS salvar do tom de voz: 'Salvar no teste' guarda como rascunho e so o chat do teste usa; 'Salvar em producao' e o mesmo salvar da aba Tom de voz e passa a valer para os atendimentos reais.",
            "'Agenda Real' faz a IA respeitar a agenda de verdade da clinica. 'Agenda Liberada' finge que esta tudo vazio, para testar o agendamento sem depender de ter horario livre no dia.",
            "'Limpar memoria' zera o que a IA lembra da conversa e recomeca do zero (nao apaga o resto do ambiente). 'Resetar ambiente' apaga do banco a conversa, o paciente, os agendamentos, as vendas, o CRM, as campanhas simuladas e o consumo do teste, cria um ambiente novo e nao tem volta: ele pede confirmacao antes.",
            "No simulador de confirmacao de agendamento o template chega SEM os botoes Confirmar/Cancelar, de proposito: a ideia e ver a IA reagindo a resposta escrita do paciente.",
            "O link de agendamento gerado dentro do teste tambem e de teste: abre com um aviso amarelo no topo e nao cria nada na agenda real.",
            "O ambiente de teste e liberado para admin e supervisor.",
        ],
    },
    {
        id: "conexoes",
        label: "Conexoes",
        route: "/suporte?tab=conexoes",
        tours: [
            { label: "Conectar um canal", url: "/whatsapp-connection?tour=conexoes-tour" },
            { label: "Templates", url: "/whatsapp-connection?tab=templates&tour=conexoes-templates" },
        ],
        resolves: [
            "como conectar o WhatsApp (oficial ou nao oficial) e o Instagram",
            "diferenca entre numero oficial e nao oficial",
            "como criar e acompanhar templates",
            "como colocar imagem, video, PDF ou localizacao fixos no cabecalho do template",
            "como colocar botoes no template (resposta rapida, link, telefone, cupom)",
            "o que e qualidade e limite diario da Meta",
            "meu numero foi restringido pela Meta, e agora",
            "a conexao caiu / QR code",
            "erro Register endpoint is not available for SMB businesses ao conectar o numero oficial",
        ],
        steps: [
            "Abra Conexoes no menu lateral (aba Conexoes).",
            "Nao oficial: adicione a instancia e leia o QR code com o WhatsApp do celular.",
            "Oficial (Meta): use o botao de conexao com a Meta e siga o cadastro ate o numero ficar registrado.",
            "A aba Templates lista os modelos aprovados, com o status de cada um.",
            "Cabecalho do template: aba Templates > Novo template > campo Cabecalho. Opcoes: Sem cabecalho, Texto, Imagem (JPG/PNG ate 5 MB), Video (MP4 ate 16 MB), Documento (PDF ate 100 MB) ou Localizacao (latitude, longitude, nome e endereco).",
            "Botoes do template: no bloco Botoes clique em 'Adicionar botao' e escolha o tipo — Resposta rapida, Abrir link (URL fixa), Ligar (telefone fixo) ou Copiar codigo (cupom fixo). Ate 10 botoes no total.",
        ],
        gotchas: [
            "No numero oficial so da para iniciar conversa com template aprovado; texto livre so dentro da janela de 24h apos a ultima mensagem do cliente.",
            "Qualidade baixa ou limite de nivel baixo derruba disparos grandes — confira o painel de qualidade antes da campanha.",
            "Nome de exibicao recusado pela Meta bloqueia envios: aparece um aviso ambar no card da conexao com os passos.",
            "Tudo no cabecalho e nos botoes e FIXO por template: a mesma imagem, video, PDF, localizacao, link, telefone e cupom vao em todos os envios (chat, nova mensagem e campanhas) e nao da para escolher outro na hora do disparo. Para trocar, edite o template — ele volta para revisao da Meta.",
            "Template com cabecalho de midia/localizacao sem o arquivo ou o ponto salvo (por exemplo, criado direto no painel da Meta e trazido pelo Sincronizar) nao aparece na lista de campanhas e mostra aviso ambar na aba Templates: edite o template e preencha para liberar o envio. Vale o mesmo para botao de cupom sem codigo salvo.",
            "Limites de botoes da Meta: no maximo 10 botoes, sendo ate 2 de link, 1 de telefone e 1 de cupom; cada texto tem ate 25 caracteres e nao pode repetir. O cupom tem ate 15 caracteres. O sistema agrupa as respostas rapidas no fim sozinho (exigencia da Meta).",
            "Botao de link com variavel ({{1}} na URL) nao pode ser usado em campanha — o disparo nao coleta esse valor por contato, entao o template fica de fora da lista.",
            "Erro 'Register endpoint is not available for SMB businesses' no cadastro do numero oficial: e um numero de coexistencia (continua ativo no app WhatsApp Business). A Meta ja registra esse numero sozinha e bloqueia a etapa de registro — o sistema passou a pular essa etapa. Se reaparecer, peca para o cliente atualizar o app WhatsApp Business (minimo 2.24.17) e refazer o cadastro ate o fim sem fechar a janela da Meta.",
            "A mensagem de Confirmacao 24h nao cita mais o nome do profissional (agora usa nome do cliente, horario, clinica e servico). Motivo: o sistema so guarda o nome da SALA do agendamento, e em sala avulsa (Sala 2, Consultorio 1) o paciente recebia 'procedimento de Botox com Sala 2'. No WhatsApp nao oficial a mudanca ja vale para todos. No oficial vale para os templates enviados a aprovacao a partir de agora: numeros ja conectados seguem com o template aprovado pela Meta e, para tirar o profissional, e preciso editar o template na aba Templates de Conexoes (o template volta para revisao da Meta e a confirmacao fica parada ate reaprovar).",
        ],
    },
    {
        id: "financeiro",
        label: "Financeiro",
        route: "/suporte?tab=financeiro",
        tours: [{ label: "Conhecer a pagina", url: "/financial?tour=financeiro-visao-geral" }],
        resolves: [
            "onde vejo o total orcado, aprovado, rejeitado e pendente",
            "quanto de dinheiro esta parado esperando resposta do cliente",
            "quais servicos sao mais orcados e quem mais faz orcamento",
            "onde vejo a lista de todas as vendas realizadas",
            "faturamento por atendente e por profissional",
            "como criar um orcamento sem abrir a conversa do cliente",
            "por que o valor aprovado nao bate com o valor orcado",
        ],
        steps: [
            "Abra Financeiro no menu lateral (fica logo abaixo de Marketing).",
            "Aba Orcamentos: escolha o periodo no topo (todo o periodo, hoje, 7 dias, 30 dias ou personalizado) — ele vale para os 4 cards de valores.",
            "Os cards mostram, em reais: Valores totais, Valores aprovados (valor final vendido), Valores rejeitados (recusados + expirados) e Valores pendentes.",
            "Abaixo vem o grafico dos ultimos 12 meses em QUANTIDADE de itens (realizados, fechados, perdidos e pendentes), com botao para alternar entre linhas e barras.",
            "A tabela 'Orcamentos realizados' lista uma linha por orcamento, mais recente no topo; clicar no nome do cliente abre a ficha dele na aba Orcamentos.",
            "No rodape da aba ficam 'Orcamentos por profissional' e 'Ranking de servicos orcados' (top 10), cada um com seu proprio filtro de periodo.",
            "Aba Vendas: escolha mes e ano; alem dos cards e graficos, ha a tabela 'Vendas realizadas' (todas as vendas, mais recente no topo), o ranking 'Mais Vendidos' e o faturamento por atendente e por profissional.",
            "Para criar um orcamento sem abrir a conversa, use o botao 'Criar orcamento' no topo da aba Orcamentos e busque o cliente por nome ou numero.",
        ],
        gotchas: [
            "O filtro de periodo do topo vale SOMENTE para os 4 cards. O grafico e sempre dos ultimos 12 meses, a tabela sempre traz os mais recentes e os dois quadros do rodape tem filtros proprios.",
            "Cards sao em REAIS e o grafico e em QUANTIDADE de itens (um orcamento com 3 servicos conta 3) — por isso os numeros nao se comparam entre si.",
            "'Valores aprovados' usa o valor FINAL da venda, ja com o desconto dado no assistente; por isso costuma ficar abaixo do valor orcado.",
            "'Valores rejeitados' soma recusados MAIS expirados.",
            "O 'Ranking de servicos orcados' e sobre o servico OFERECIDO — nao tem relacao com o campo Indicacao (de onde veio o cliente).",
            "Em 'Orcamentos por profissional' aparecem todos os profissionais ativos, inclusive com zero, para o gestor enxergar quem nao esta orcando.",
            "No faturamento por profissional, vendas antigas sem profissional vinculado somam em 'Sem responsavel'.",
            "As tabelas carregam os 300 registros mais recentes; para o historico completo de um cliente, clique no nome dele e abra a ficha.",
            "Financeiro e modulo com permissao: admin ve sempre; supervisor e atendente so veem o item no menu se a permissao do modulo Financeiro estiver ligada em Equipe > Permissoes. O botao 'Criar orcamento' respeita a permissao do modulo Orcamentos.",
        ],
    },
    {
        id: "configuracoes",
        label: "Configuracoes",
        route: "/suporte?tab=configuracoes",
        tours: [{ label: "Conhecer a pagina", url: "/settings?tour=config-tour" }],
        resolves: [
            "como mudar dados da empresa, senha e foto",
            "como ativar o menu agrupado e as notificacoes",
            "como criar e organizar tags",
            "como configurar o encerramento automatico de conversas",
            "por que conversas antigas continuam pendentes mesmo com o encerramento ligado",
            "o que faz a opcao fechar conversas sem interacao",
            "quais e-mails o sistema envia",
        ],
        steps: [
            "Abra Configuracoes no menu lateral.",
            "Abas: Perfil, Empresa, Seguranca, Sistema (menu agrupado e notificacoes), Tags e Automacoes.",
            "Na aba Empresa ficam o nome da empresa e o bloco 'Orcamento em PDF' (cabecalho em PNG 2400x400 com modelo para baixar + rodape em texto livre). Detalhes na aba Orcamentos do manual.",
            "Em Automacoes ficam o encerramento automatico, a mensagem de aviso e a instancia padrao dos disparos.",
            "O cartao de encerramento tem DUAS chaves independentes: a chave do titulo (aviso + mensagem final, conta a partir da ultima mensagem DO CLIENTE) e a chavinha 'Fechar conversas sem interacao' (encerra em silencio, conta a partir da ultima mensagem da conversa).",
        ],
        gotchas: [
            "SAO DUAS REGRAS DIFERENTES. A chave do titulo (Encerramento Automatico de Mensagens) avisa e depois encerra com mensagem. A chavinha 'Fechar conversas sem interacao' encerra SEM MENSAGEM nenhuma e funciona mesmo com a chave do titulo desligada. Se o cliente diz que tem conversa parada ha dias ainda pendente, quase sempre a chave do titulo esta DESLIGADA.",
            "'Fechar conversas sem interacao' vale para toda conversa parada alem do limite (padrao 48h, configuravel). Por padrao so encerra quando a ULTIMA MENSAGEM FOI DA EMPRESA (IA ou operador). Se foi o cliente quem falou por ultimo, o ticket continua aberto de proposito — a resposta ainda e nossa. Para encerrar esses tambem existe a opcao 'Encerrar tambem quando a ultima mensagem foi do cliente', desligada por padrao.",
            "O relogio de 'sem interacao' e a ultima mensagem da conversa, de qualquer lado; o relogio da chave do titulo e a ultima mensagem do cliente. Nos dois casos as pilulas cinzas (transferencia de fila, 'fulano visualizou essa conversa', entrou/saiu do grupo) NAO reiniciam a contagem.",
            "Ao ligar qualquer das duas chaves numa conta com backlog, o sistema encerra as conversas atrasadas em lote nas varreduras seguintes (a cada 5 minutos, ate 200 por vez) e cada card ativo do CRM vai para Sem Contato. Avise o cliente antes de ligar.",
            "O encerramento automatico so nasce ligado em contas novas; contas antigas precisam ligar manualmente.",
            "O prazo do encerramento conta sempre a partir da ultima mensagem DO CLIENTE — se ele responder, o ciclo zera.",
            "A mensagem final e enviada no mesmo instante em que a conversa e arquivada; o aviso de entrega do WhatsApp chega segundos depois e o sistema aplica esse status no historico por ate 15 minutos apos o encerramento. Se o recibo demorar mais que isso, a mensagem fica marcada como 'Enviada' no historico mesmo tendo sido entregue.",
            "Grupos e Instagram ficam de fora do encerramento automatico.",
            "Cliente dentro do ciclo de confirmacao de agendamento e IGNORADO pelo encerramento automatico: da mensagem de confirmacao (vespera) ate a pesquisa de satisfacao (um dia depois do atendimento) o ticket nao recebe aviso nem e fechado. Quem fecha esse ticket e o proprio fluxo — na hora em que o cliente responde a pesquisa, ou 24h depois se ele nao responder.",
            "Todo e-mail da Clinbia sai de nao-responda@clinbia.ai e segue o mesmo layout: barra e cabecalho azuis com a logo branca, conteudo em cartao branco e rodape cinza com a logo azul e a assinatura 'Clinbia – Atendimento e Gestao de Leads com IA'. Os links de acao sempre apontam para app.clinbia.ai. Se o cliente receber algo fora desse padrao, ou que peca a senha dele por e-mail, NAO e da Clinbia — a Clinbia nunca pede senha por e-mail.",
        ],
    },
    {
        id: "atendimento",
        label: "Falar com o suporte",
        route: "/suporte?tab=atendimento",
        tours: [{ label: "Onde fica o botao", url: "/?tour=suporte-chat" }],
        resolves: [
            "como falar com o suporte da Clinvia",
            "onde vejo meus chamados antigos",
            "onde chegam os avisos de atualizacao do sistema",
        ],
        steps: [
            "Clique no botao azul de fone no canto inferior esquerdo.",
            "Aba Suporte: escreva a duvida — o assistente responde na hora e chama a equipe quando precisa.",
            "Botao 'Ver chamados antigos' abre o historico das conversas anteriores.",
            "Aba Avisos: novidades e correcoes publicadas pela equipe da Clinvia.",
        ],
        gotchas: [
            "Cada pessoa tem o proprio chat: ninguem da equipe ve o chamado do colega, nem o dono da conta.",
        ],
    },
];

/** Versao compacta usada no system prompt (links ja absolutos). */
export const KNOWLEDGE_SUMMARY = SUPPORT_TOPICS.map((t) => {
    const tours = t.tours?.length
        ? `\n  Tours: ${t.tours.map((x) => `${x.label} -> ${abs(x.url)}`).join(" | ")}`
        : "";
    return [
        `### ${t.label} (id: ${t.id}) — manual: ${abs(t.route)}${tours}`,
        `  Resolve: ${t.resolves.join("; ")}`,
        `  Passos: ${t.steps.map((s, i) => `${i + 1}) ${s}`).join(" ")}`,
        t.gotchas?.length ? `  Atencao: ${t.gotchas.join(" ")}` : "",
    ]
        .filter(Boolean)
        .join("\n");
}).join("\n\n");

/** Devolve o topico com os links ja absolutos (a IA precisa colar URL clicavel). */
export function getTopic(id: string): SupportTopic | null {
    const key = (id || "").trim().toLowerCase();
    const topic = SUPPORT_TOPICS.find((t) => t.id === key);
    if (!topic) return null;
    return {
        ...topic,
        route: abs(topic.route),
        tours: topic.tours?.map((t) => ({ ...t, url: abs(t.url) })),
    };
}

export const TOPIC_IDS = SUPPORT_TOPICS.map((t) => t.id);
