// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// TEMPORARY FIX: Hardcoded to force production use
const SUPABASE_URL = "https://swfshqvvbohnahdyndch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3ZnNocXZ2Ym9obmFoZHluZGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1OTAyMzIsImV4cCI6MjA3OTE2NjIzMn0.rUja2PsYj9kWODdizhJNS6HjfA9Tg7DrJJylUH8RTnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    // Origem DECLARADA do incidente (23/09/2026). Sem isto o monitoramento
    // deduz "front" pelo formato do JWT ou pelo Referer e marca
    // `origem_inferida = true`. Uma linha aqui cobre TODA chamada do app —
    // PostgREST e edge function — porque o supabase-js aplica estes headers
    // em ambos.
    headers: { "x-origin": "front" },
  },
});